### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by janwo** [nextzen/nextzen.js#363]
What about Typescript support? Would appreciate it 👍

**Comment by hanbyul-here** [comment]
Hi ! Thanks for checking out Mapzen.js. We unfortunately don't have much experience with Typescript. Can you provide more context what type script requires for us?

**Comment by janwo** [comment]
Hi Hanbyul :)
It's actually not a big deal, the whole module just becomes typed. Check this short article out to get started: http://www.erikschierboom.com/2015/11/04/building-a-javascript-library-part-6-typescript/

This would help many developers using Typescript. 👍
