### ISSUE TITLE
Update to Tangram v0.15

### ISSUE THREAD

**Issue by nvkelso** [nextzen/nextzen.js#457]
The new v0.15.2 came out but looks like this is still pegged to v0.14?

**Comment by hanbyul-here** [comment]
I am working on this, but Tangram 0.15.2 doesn't seem to be available through NPM. Did 0.15.2 get released?

**Comment by nvkelso** [comment]
@meetar Can you check the new Tangram JS 0.15.2 was also published to NPM, please?

**Comment by nvkelso** [comment]
@hanbyul-here Tangram JS v0.15.3 is now published to NPM, unblocking you from new release here in Nextzen.js.

**Comment by hanbyul-here** [comment]
PR opened for this : https://github.com/nextzen/nextzen.js/pull/458
